### ISSUE TITLE
algorytm liczący punkty

### ISSUE THREAD

**Issue by piotrguldur** [mtrojanowski/ranking#4]
Dodałem kolejny turniej i zauważyłem, że algorytm źle podlicza wyniki.
Przyelejam zasady algorytmu:

Rozróżniamy 4 rodzaje turniejów
 - lokalny
-  master indywidualny
-  master drużynowy
-  master parowy
W rankingu liczymy 10 najlepszych turniejów danego gracza według następującego schematu:
-  turnieje lokalne nie mają ograniczeń
-  do rankingu w pełni liczą się maksymalnie 4 mastery, w tym maksymalnie 2 mastery drużynowe oraz maksymalnie jeden master parowy (czyli w rankingu mogą być np. 1 mastery indywidualny + 2 mastery drużynowe + 1 master parowy)
-  każdy master powyżej 4 (a dla masterów drużynowych powyżej 2 oraz parowych powyżej pierwszego), który nie wlicza się już do rankingu danego gracza (np. dany gracz ma lepsze wyniki z innych masterów) liczą się do rankingu jako turnieje lokalne z jednym zastrzeżeniem, iż punkty za nie zdobyte są dzielone przez 3 (np. jeśli gracz na masterze, który nie wlicza się do jego najlepszych turniejów zdobył 150 pkt. to za ten turniej sklasyfikowany jako lokal na potrzeby rankingu dany gracz otrzyma 50 pkt, o ile nie ma lepszych wyników z innych lokali)
- do rankingu liczą się również premie sędziowskie – maksymalnie 2 premie. Premie sędziowskie są sklasyfikowane jako turnieje lokalne. Pierwsza premia sędziowska jest warta 150 pkt. Druga natomiast 100 pkt.

Na razie widzę błędy na trzech graczach:
- Big Boss (id 2454) - ma rozegrane 11 turniejów, więc powinien mu się nie liczyć najgorszy lokal (lokal o id 6040 za który miał 1 pkt), natomiast algorytm tak jakby uciął mu jednego mastera (id 6013)
- Bobson (id 4229) - ma już zagranych 5 masterów, więc jeden powinien mu się liczyć jako lokal za 1/3 pkt, natomiast do rankingu wlicza mu całość
- Handełek (id 2230) - taki sam przypadek jak u Bobsona

**Comment by mtrojanowski** [comment]
W rankingu obecnie mastery parowe traktowane są jak drużynowe. Zgodnie z regulaminem:

> 7.3 Do rankingu liczy się dziesięć najlepszych wyników z turniejów lub z lig lokalnych danego gracza, przy czym maksymalnie cztery wyniki z turniejów klasy master (w tym maksymalnie 2 mastery drużynowe). 

To niedopatrzenie, że nie ma informacji o parówkach? 

Z tym, że nie jestem pewien czy błędy, o których piszesz na pewno wynikają z tego przeoczenia. Sprawdzę dokładnie te przypadki i dam znać.

**Comment by piotrguldur** [comment]
Ten regulamin chyba nie jest aktualny - wyżej w poście wkleiłem info i tam właśnie jest mowa o parówkach.

**Comment by mtrojanowski** [comment]
Poprawiłem algorytm żeby liczył według tego co jest w pierwszym poście. Dodałem też widok wyników indywidualnych więc będzie można łatwiej kontrolować czy wszystko jest ok.
